on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: amadran/msp430-gcc-9.3.1.11:latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - run: make
      - run: make cppcheck
